const countryList = [
    { isoCode: 'AL', name: 'Albania' },
    { isoCode: 'DZ', name: 'Algeria' },
    { isoCode: 'AO', name: 'Angola' },
    { isoCode: 'AR', name: 'Argentina' },
    { isoCode: 'AM', name: 'Armenia' },
    { isoCode: 'AU', name: 'Australia' },
    { isoCode: 'AT', name: 'Austria' },
    { isoCode: 'AZ', name: 'Azerbaijan' },
    { isoCode: 'BS', name: 'Bahamas' },
    { isoCode: 'BH', name: 'Bahrain' },
    { isoCode: 'BD', name: 'Bangladesh' },
    { isoCode: 'BY', name: 'Belarus' },
    { isoCode: 'BE', name: 'Belgium' },
    { isoCode: 'BZ', name: 'Belize' },
    { isoCode: 'BO', name: 'Bolivia, Plurinational State of' },
    { isoCode: 'BA', name: 'Bosnia and Herzegovina' },
    { isoCode: 'BW', name: 'Botswana' },
    { isoCode: 'BR', name: 'Brazil' },
    { isoCode: 'BN', name: 'Brunei Darussalam' },
    { isoCode: 'BG', name: 'Bulgaria' },
    { isoCode: 'BF', name: 'Burkina Faso' },
    { isoCode: 'CV', name: 'Cabo Verde' },
    { isoCode: 'KH', name: 'Cambodia' },
    { isoCode: 'CA', name: 'Canada' },
    { isoCode: 'KY', name: 'Cayman Islands' },
    { isoCode: 'TD', name: 'Chad' },
    { isoCode: 'CL', name: 'Chile' },
    { isoCode: 'CN', name: 'China' },
    { isoCode: 'CO', name: 'Colombia' },
    { isoCode: 'CD', name: 'Congo, The Democratic Republic of the' },
    { isoCode: 'CK', name: 'Cook Islands' },
    { isoCode: 'CR', name: 'Costa Rica' },
    { isoCode: 'HR', name: 'Croatia' },
    { isoCode: 'CU', name: 'Cuba' },
    { isoCode: 'CY', name: 'Cyprus' },
    { isoCode: 'CZ', name: 'Czechia' },
    { isoCode: 'DK', name: 'Denmark' },
    { isoCode: 'DO', name: 'Dominican Republic' },
    { isoCode: 'EC', name: 'Ecuador' },
    { isoCode: 'EG', name: 'Egypt' },
    { isoCode: 'SV', name: 'El Salvador' },
    { isoCode: 'EE', name: 'Estonia' },
    { isoCode: 'SZ', name: 'Eswatini' },
    { isoCode: 'ET', name: 'Ethiopia' },
    { isoCode: 'FI', name: 'Finland' },
    { isoCode: 'FR', name: 'France' },
    { isoCode: 'PF', name: 'French Polynesia' },
    { isoCode: 'GE', name: 'Georgia' },
    { isoCode: 'DE', name: 'Germany' },
    { isoCode: 'GH', name: 'Ghana' },
    { isoCode: 'GR', name: 'Greece' },
    { isoCode: 'GP', name: 'Guadeloupe' },
    { isoCode: 'GU', name: 'Guam' },
    { isoCode: 'GT', name: 'Guatemala' },
    { isoCode: 'HK', name: 'Hong Kong' },
    { isoCode: 'HU', name: 'Hungary' },
    { isoCode: 'IS', name: 'Iceland' },
    { isoCode: 'IN', name: 'India' },
    { isoCode: 'ID', name: 'Indonesia' },
    { isoCode: 'IR', name: 'Iran, Islamic Republic of' },
    { isoCode: 'IQ', name: 'Iraq' },
    { isoCode: 'IE', name: 'Ireland' },
    { isoCode: 'IL', name: 'Israel' },
    { isoCode: 'IT', name: 'Italy' },
    { isoCode: 'JM', name: 'Jamaica' },
    { isoCode: 'JP', name: 'Japan' },
    { isoCode: 'JO', name: 'Jordan' },
    { isoCode: 'KZ', name: 'Kazakhstan' },
    { isoCode: 'KE', name: 'Kenya' },
    { isoCode: 'KR', name: 'Korea, Republic of' },
    { isoCode: 'XK', name: 'Kosovo' },
    { isoCode: 'KW', name: 'Kuwait' },
    { isoCode: 'KG', name: 'Kyrgyzstan' },
    { isoCode: 'LV', name: 'Latvia' },
    { isoCode: 'LB', name: 'Lebanon' },
    { isoCode: 'LR', name: 'Liberia' },
    { isoCode: 'LY', name: 'Libya' },
    { isoCode: 'LT', name: 'Lithuania' },
    { isoCode: 'LU', name: 'Luxembourg' },
    { isoCode: 'MO', name: 'Macao' },
    { isoCode: 'MG', name: 'Madagascar' },
    { isoCode: 'MY', name: 'Malaysia' },
    { isoCode: 'MV', name: 'Maldives' },
    { isoCode: 'ML', name: 'Mali' },
    { isoCode: 'MT', name: 'Malta' },
    { isoCode: 'MR', name: 'Mauritania' },
    { isoCode: 'MU', name: 'Mauritius' },
    { isoCode: 'MX', name: 'Mexico' },
    { isoCode: 'MN', name: 'Mongolia' },
    { isoCode: 'ME', name: 'Montenegro' },
    { isoCode: 'MA', name: 'Morocco' },
    { isoCode: 'MZ', name: 'Mozambique' },
    { isoCode: 'MM', name: 'Myanmar' },
    { isoCode: 'NA', name: 'Namibia' },
    { isoCode: 'NP', name: 'Nepal' },
    { isoCode: 'NL', name: 'Netherlands' },
    { isoCode: 'NZ', name: 'New Zealand' },
    { isoCode: 'NE', name: 'Niger' },
    { isoCode: 'NG', name: 'Nigeria' },
    { isoCode: 'MK', name: 'North Macedonia' },
    { isoCode: 'NO', name: 'Norway' },
    { isoCode: 'OM', name: 'Oman' },
    { isoCode: 'PK', name: 'Pakistan' },
    { isoCode: 'PA', name: 'Panama' },
    { isoCode: 'PG', name: 'Papua New Guinea' },
    { isoCode: 'PE', name: 'Peru' },
    { isoCode: 'PH', name: 'Philippines' },
    { isoCode: 'PL', name: 'Poland' },
    { isoCode: 'PT', name: 'Portugal' },
    { isoCode: 'PR', name: 'Puerto Rico' },
    { isoCode: 'QA', name: 'Qatar' },
    { isoCode: 'RO', name: 'Romania' },
    { isoCode: 'RU', name: 'Russian Federation' },
    { isoCode: 'RW', name: 'Rwanda' },
    { isoCode: 'SA', name: 'Saudi Arabia' },
    { isoCode: 'SN', name: 'Senegal' },
    { isoCode: 'RS', name: 'Serbia' },
    { isoCode: 'SC', name: 'Seychelles' },
    { isoCode: 'SL', name: 'Sierra Leone' },
    { isoCode: 'SG', name: 'Singapore' },
    { isoCode: 'SX', name: 'Sint Maarten (Dutch part)' },
    { isoCode: 'SK', name: 'Slovakia' },
    { isoCode: 'SI', name: 'Slovenia' },
    { isoCode: 'SO', name: 'Somalia' },
    { isoCode: 'ZA', name: 'South Africa' },
    { isoCode: 'SS', name: 'South Sudan' },
    { isoCode: 'ES', name: 'Spain' },
    { isoCode: 'LK', name: 'Sri Lanka' },
    { isoCode: 'SD', name: 'Sudan' },
    { isoCode: 'SE', name: 'Sweden' },
    { isoCode: 'CH', name: 'Switzerland' },
    { isoCode: 'SY', name: 'Syrian Arab Republic' },
    { isoCode: 'TW', name: 'Taiwan, Province of China' },
    { isoCode: 'TZ', name: 'Tanzania, United Republic of' },
    { isoCode: 'TH', name: 'Thailand' },
    { isoCode: 'TN', name: 'Tunisia' },
    { isoCode: 'TR', name: 'Turkey' },
    { isoCode: 'TM', name: 'Turkmenistan' },
    { isoCode: 'UG', name: 'Uganda' },
    { isoCode: 'UA', name: 'Ukraine' },
    { isoCode: 'AE', name: 'United Arab Emirates' },
    { isoCode: 'GB', name: 'United Kingdom' },
    { isoCode: 'US', name: 'United States' },
    { isoCode: 'UY', name: 'Uruguay' },
    { isoCode: 'UZ', name: 'Uzbekistan' },
    { isoCode: 'VE', name: 'Venezuela, Bolivarian Republic of' },
    { isoCode: 'VN', name: 'Viet Nam' },
    { isoCode: 'ZM', name: 'Zambia' },
    { isoCode: 'ZW', name: 'Zimbabwe' }
]

export default countryList;